#!/bin/bash

set -o errexit
set -o nounset

# in NAUTILUS_SCRIPT_SELECTED_FILE_PATHS files are separated by newlines and
# not spaces so set IFS to newline.
IFS=$'\n'
PDFARGUMENTS=()
PDFDIR=""

# support NAUTILUS + NEMO + CAJA
if [[ -n "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS-}" ]]; then
    FPATHS="${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}"
elif [[ -n "${NEMO_SCRIPT_SELECTED_FILE_PATHS-}" ]]; then
    FPATHS="${NEMO_SCRIPT_SELECTED_FILE_PATHS}"
elif [[ -n "${CAJA_SCRIPT_SELECTED_FILE_PATHS-}" ]]; then
    FPATHS="${CAJA_SCRIPT_SELECTED_FILE_PATHS}"
fi

filename=""
for file in ${FPATHS}
do
  if [[ -f "${file}" ]]; then
      ext=${file##*.}
      if [[ "${ext}" == "pdf" ]]; then
          PDFARGUMENTS+=("${file}")
          filename=$(basename "${file}" .pdf)
          filename=${filename// /}
          PDFDIR=$(dirname "${file}")/"${filename}"
      fi
  fi
done

if (( ${#PDFARGUMENTS[@]} )); then
    mkdir "${PDFDIR}"
    cd "${PDFDIR}" || exit
    pdftk "${PDFARGUMENTS[@]}" burst output "${filename}"_%02d.pdf
    zenity --info --text="PDF burst to ${PDFDIR}"
fi
